## Numpy Fundamentals

#### Creating Numpy Arrays

In [33]:
# np.array
import numpy as np
# 1D np array also called vector
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [34]:
# 2D np array also called matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [35]:
# 3D np array also called tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### You can create any datatype of your np array by using dtype=datatype see below.

In [36]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [37]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [38]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

##### np.arange(a,b,c) included a and excluded b and c is used to skip/gap that much character or etc

In [39]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

##### with reshape(a,b) -->> a rows and b columns where a*b must be equal to no of elements or numbers present

In [54]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [55]:
np.arange(1,11).reshape(5,5)

ValueError: cannot reshape array of size 10 into shape (5,5)

##### np.ones and np.zeros -->> to initializes the values of anything(let say initialising an array) anywhere
##### Also NOTE that by default while you generate any values in np array it will be float

In [47]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
# To generate random values we use
np.random.random((3,5))

array([[0.52713692, 0.28948037, 0.43443262, 0.07363903, 0.64679707],
       [0.0220114 , 0.24266978, 0.90152869, 0.14581354, 0.83051891],
       [0.77638333, 0.97449462, 0.0320333 , 0.64351824, 0.61035596]])

##### np.linspace(a,b,c) -->> generates c nos of random values b/w a and c such that each are at same distant or equidistant

In [50]:
#np.linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [52]:
# If you want to change the datatype of generated value which is float by default you can do so...
np.linspace(-10,10,5,dtype=int)

array([-10,  -5,   0,   5,  10])

##### np.identity -->> to generates an identity matrix

In [51]:
# identity matrix whose diagonal elements are 1 and all others are zero
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Array Attributes

In [58]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [66]:
#ndim -->> no of dimensions
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [71]:
# shape -->> shows how many rows and columns are there and definitely it will also show the dimension
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [73]:
# size -->> no of elements in given array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [80]:
# itemsize -->> tells us how much size is occupied by each item in a memory of RAM
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)
# This is because each item of a1 and a3 are integer but a2 ka each item is float

4
8
4


##### NOTE: int32  occupies 4byte space in memory but int64 occupies 8byte space in memory

In [81]:
#dtype -->> tell us the datatype of your items
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


#### Changing Datatype

In [84]:
# np array a2 have datatype of float64  but if we want to change it we can change it by
a2.dtype

dtype('float64')

In [85]:
a2.astype(np.float32)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [86]:
#Similarly for a1 and a3 -->> Since already in int32 you can check below by
a1.dtype

dtype('int32')

In [87]:
a1.astype(np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

##### NOTE: You can also convert int into float and vice-versa etc

In [88]:
a1.astype(np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### Array Operations

In [93]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


##### Scalar operations -->> All Arithmetic Operations you can perform

In [99]:
print(a1 + 2)  #Addition
print(a1 - 2)  #Subtraction
print(a1*2)    #Multiplication
print(a1/4)    #Division
print(a1**3)   #Power

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.   0.25 0.5  0.75]
 [1.   1.25 1.5  1.75]
 [2.   2.25 2.5  2.75]]
[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]]


##### Relational -->> All the relational operations you can use and answer for each element will be either true or false

In [110]:
print(a2>5)
print(a2>15)
print(a2 == 20)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [ True False False False]]


##### Vector operations
##### Arithmetic-->>All the arithmatic operations you can do on both array(+,-,*,/,pow etc)-->>Order must be same of both array

In [111]:
print(a1)
print(a2)
print(a1+a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


##### max/min/sum/product

##### mean/median/standard/var

##### trignometric functions

In [ ]:
trigmometric fu 

##### dot product