## Numpy Fundamentals

#### Creating Numpy Arrays

In [33]:
# np.array
import numpy as np
# 1D np array also called vector
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [34]:
# 2D np array also called matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [35]:
# 3D np array also called tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### You can create any datatype of your np array by using dtype=datatype see below.

In [36]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [37]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [38]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

##### np.arange(a,b,c) included a and excluded b and c is used to skip/gap that much character or etc

In [39]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

##### with reshape(a,b) -->> a rows and b columns where a*b must be equal to no of elements or numbers present

In [54]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [55]:
np.arange(1,11).reshape(5,5)

ValueError: cannot reshape array of size 10 into shape (5,5)

##### np.ones and np.zeros -->> to initializes the values of anything(let say initialising an array) anywhere
##### Also NOTE that by default while you generate any values in np array it will be float

In [47]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
# To generate random values we use
np.random.random((3,5))

array([[0.52713692, 0.28948037, 0.43443262, 0.07363903, 0.64679707],
       [0.0220114 , 0.24266978, 0.90152869, 0.14581354, 0.83051891],
       [0.77638333, 0.97449462, 0.0320333 , 0.64351824, 0.61035596]])

##### np.linspace(a,b,c) -->> generates c nos of random values b/w a and c such that each are at same distant or equidistant

In [50]:
#np.linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [52]:
# If you want to change the datatype of generated value which is float by default you can do so...
np.linspace(-10,10,5,dtype=int)

array([-10,  -5,   0,   5,  10])

##### np.identity -->> to generates an identity matrix

In [51]:
# identity matrix whose diagonal elements are 1 and all others are zero
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Array Attributes

In [58]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [66]:
#ndim -->> no of dimensions
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [71]:
# shape -->> shows how many rows and columns are there and definitely it will also show the dimension
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [73]:
# size -->> no of elements in given array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [80]:
# itemsize -->> tells us how much size is occupied by each item in a memory of RAM
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)
# This is because each item of a1 and a3 are integer but a2 ka each item is float

4
8
4


##### NOTE: int32  occupies 4byte space in memory but int64 occupies 8byte space in memory

In [81]:
#dtype -->> tell us the datatype of your items
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


#### Changing Datatype

In [84]:
# np array a2 have datatype of float64  but if we want to change it we can change it by
a2.dtype

dtype('float64')

In [85]:
a2.astype(np.float32)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [86]:
#Similarly for a1 and a3 -->> Since already in int32 you can check below by
a1.dtype

dtype('int32')

In [87]:
a1.astype(np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

##### NOTE: You can also convert int into float and vice-versa etc

In [88]:
a1.astype(np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### Array Operations

In [93]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


##### Scalar operations -->> All Arithmetic Operations you can perform

In [99]:
print(a1 + 2)  #Addition
print(a1 - 2)  #Subtraction
print(a1*2)    #Multiplication
print(a1/4)    #Division
print(a1**3)   #Power

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.   0.25 0.5  0.75]
 [1.   1.25 1.5  1.75]
 [2.   2.25 2.5  2.75]]
[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]]


##### Relational -->> All the relational operations you can use and answer for each element will be either true or false

In [110]:
print(a2>5)
print(a2>15)
print(a2 == 20)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [ True False False False]]


##### Vector operations
##### Arithmetic-->>All the arithmatic operations you can do on both array(+,-,*,/,pow etc)-->>Order must be same of both array

In [111]:
print(a1)
print(a2)
print(a1+a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


### Array Functions

In [26]:
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[13. 90. 71.]
 [43. 48. 54.]
 [57. 99. 50.]]


##### 1.max/min/sum/product

In [27]:
#Thses max/min/sum/prod will give output of all the elements but if you want it byy row wise and column wise see below
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.product(a1))
# NOTE: Instead of product you cam also use prod

99.0
13.0
525.0
2612328074928000.0


In [28]:
# max(a1,axis = 1) means print all the max element of each row bcz 1 means row
# max(a1,axis = 1) means print all the max element of each column bcz 0 means column
print(np.max(a1,axis = 1))
print(np.min(a1,axis = 0))
print(np.sum(a1,axis = 1))
print(np.product(a1,axis = 0))

[90. 54. 99.]
[13. 48. 50.]
[174. 145. 206.]
[ 31863. 427680. 191700.]


In [29]:
# Means print all the max element from each column bcz axis=0 means column and axis=1 means row
np.max(a1,axis=0)

array([57., 99., 71.])

##### 2.mean/median/standard/var

In [32]:
#NOTE: Here also you can use axis=0 for column and axis=1 for row
print(np.mean(a1))
print(np.median(a1))
print(np.var(a1))
print(np.mean(a1,axis=1))

58.333333333333336
54.0
589.3333333333334
[58.         48.33333333 68.66666667]


##### 3.trignometric functions

In [134]:
# You can use all trignometric functions present but there is no use of it in whole DataScience
np.sin(a1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

##### dot product-->> for dot product of two matrix (a,b) & (c,d) here b=c necessary condition and resultant will be of (a,d) order

In [135]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
print(np.dot(a2,a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[114 120 126]
 [378 400 422]
 [642 680 718]]


##### 4.log and exponents

In [139]:
print(np.log(a1))
print(np.exp(a1))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


C:\Users\deepu\AppData\Local\Temp\ipykernel_19712\1349568853.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


##### 5.round/floor/ceil
###### .round -->> round off to the nearest integer
###### .floor -->> take you to the previous integer
###### .ceil -->> take you to the next integer

In [140]:
arr = np.random.random((2,3))*100
print(arr)
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))


[[27.52498664 30.26882116 94.99262472]
 [52.120818   32.64844252 63.13359829]]
[[28. 30. 95.]
 [52. 33. 63.]]
[[27. 30. 94.]
 [52. 32. 63.]]
[[28. 31. 95.]
 [53. 33. 64.]]


In [141]:
# Or you can also write as
np.floor(np.random.random((2,3))*100)

array([[ 3.,  8., 54.],
       [29., 50., 11.]])

#### Indexing and Slicing

In [57]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [59]:
print(a1)
print(a1[0])

[0 1 2 3 4 5 6 7 8 9]
0


In [64]:
# For 2D array
print(a2)
# Let we have to print 6 so check that element is present in which row and column
print(a2[1,2]) # here 1 is row and 2 is column
#NOTE: row and column starts with 0
print(a2[1,0])
print(a2[2,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
4
11


###### Simply for finding element from 3D--> As we know 3D is made from some 2D array so first we check our element is present from which 2D array and then simply search like 2D e.g for 3D array arr we use ar[a,b,c]

In [73]:
# 3D array
print(a3)
#For element in 3D-->>first write in which 2D array your element is present(bcz 3d is made from some no of 2D) 
# then like 2D search ur element. NOTE: No of 2D ka indexing bhi start from 0 then 1 and then 2
print(a3[1,0,0])
print(a3[1,0,1])
print(a3[0,0,1])
print(a3[0,1,1])
print(a3[0,0,0])
print(a3[1,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
4
5
1
3
0
6


#### Slicing -->> fetching multiple elements at once

In [80]:
print(a1)
print(a1[2:5]) # Means print from 2 to 5 and exclude 5
print(a1[2:5:2]) # Means print from 2 to 5 alternate with excluding 5

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4]


###### Slicing in 2D array

In [110]:
print(a2)
print(a2[0,:]) #for printing 1st row(: is used bcz we want each column for any row)
print(a2[:,1]) # 2nd column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[1 5 9]


###### if you want to print 5,6 and 9,10 what will you do ??

In [111]:
a2[1:,1:3]
# here 1: means 1 onwards i.e 1 aur uske aage ke sabhi row
# Since after comma column will start so ->> 1:3 means 1 to 3 column excluded 3

array([[ 5,  6],
       [ 9, 10]])

###### if you want to print 0,3,8,11 means all corner elements

In [112]:
a2[::2,::3]
# let's see above as a2[:,:] means all row and column and we need to skip 1 row so(use :2) 
# and skip 2 col so use(:3) and finally it looks like a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

###### if you want to print 1,3,9,11 elements

In [113]:
# mistake I am doing but fix it after sometime without any help 😍
a2[::2,::-2]

array([[ 3,  1],
       [11,  9]])

In [114]:
a2[::2,1::2]
# Here ,1::2 means all columns from 1 with alternate(means 1st coumn then 3rd then 5th etc)

array([[ 1,  3],
       [ 9, 11]])

###### if you want only 4 and 7

In [115]:
a2[1,0::3]
# here 0::3 means 0 ke aage sabhi columns with skipping 2 columns (::2 rehta to 1 columns skip krte )

array([4, 7])

if you want 1,2,3,5,6,7 

In [116]:
a2[0:2,1:4]
# 0:2 means rows (0 and 1 bcz 2 is excluded)
# 1:4 means columns (1,2 and 3 bcz 4 is excluded)

array([[1, 2, 3],
       [5, 6, 7]])

###### Slicing in 3D array

In [119]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


###### if you want to print elements from 9 to 17 -->> here are two ways

In [121]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [122]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

###### if you want to print 0 to 8 and then 18 to 27

In [124]:
a3[::2]
# here a3[:] means all elements and :2 means alternate hence a3[::2] means 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

###### let's print 2nd row of 1st 2D array i.e 3,4,5

In [126]:
a3[0,1,:]
# 0 means 1st 2D array , 1 means 2nd row and : means all columns

array([3, 4, 5])

###### let's print 2nd column of 2nd 2D array i.e 10,13,16

In [128]:
a3[1,:,1]

array([10, 13, 16])

###### let's print  22,23,25,26

In [130]:
a3[2,1:3,1:3]
# Or you can do a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

###### let's print  0,2,18,20

In [133]:
a3[::2,::3,::2]
# Here ::2 means all alternate 2D array
# here ::3 means all rows from starting with gap of 2 rows
# here ::2 means all columns from starting with gap of 1 columns 
# Or you can do as a3[::2,0,::2] here 0 coz we need only 0th row of each 2D array

array([[[ 0,  2]],

       [[18, 20]]])

#### Iterating 

###### iteration in 1D array                                                                                

In [143]:
print(a1)
for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


###### iteration in 2D array -->> in each loop only one row is printed at once

In [144]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


###### iteration in 3D array -->> in each time 2D array is printed

In [155]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [156]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [158]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#### Reshaping

###### 1.reshape -->> already done above

###### 2.transpose

In [162]:
print(a2)
print(np.transpose(a2))
# or you can simply use a2.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


###### 3.ravel -->> It will convert any dimension of array into 1D

In [164]:
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


#### Stacking
###### . means adding two numpy array horizontally or vertically

###### 1.horizontal stacking

In [174]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)
np.hstack((a4,a5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [175]:
# you can do so many times you need
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [176]:
np.hstack((a5,a4,a5))

array([[12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

###### 2.Vertical stacking

In [177]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [178]:
np.vstack((a5,a4,a5))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Splitting -->> must be in same part
###### .splitting numpy array

##### NOTE: there might be confusing that in horizontal spliitting a vertical line divides both 
##### And for vertical splitting a horizontal line divides the given numpy array

In [191]:
#horizontal splitting 
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [192]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [193]:
#Vertical splitting
print(a5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [194]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [195]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]