## Numpy Advanced

#### Numpy Array vs Python Lists

###### The major differences b/w Numpy array and python list are :

##### 1.speed

In [10]:
#list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
import time

start = time.time()
for i in range (len(a)):
    c.append(a[i]+b[i])
print("The time taken to run this code is : ",time.time()-start,"seconds")


The time taken to run this code is :  5.664685487747192 seconds


In [13]:
#numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.0852975845336914


###### Now 5.66/0.08 = 70 . It means almost 70 times faster 

##### 2.memory

In [14]:
# Python list
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [16]:
# numpy array
a = np.arange(10000000)
sys.getsizeof(a)
# NOTE: In this laptop by default int datatype is int32 but in another it will int64 where it occupies memory as same of list
#So we can convert datatype of int64 to int 32 & memory occupy will be reduced here by default it'sint32 so no need to change

40000112

###### Conclusion : Numpy array almost occupy half memory as of python list

##### 3.convenience

In [17]:
# Convenience means that in python list to add numbers from 0 to 2Cr we've to run loop and have to write code but in
# Numpy array simply do addition i.e c = a + b which is more and more convenient

#### Advance Indexing

##### 1.Normal Indexing and Slicing

In [35]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
a[1,2]

5

In [37]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

##### 2.Fancy Indexing -->> When no simple pattern is observed (You've to provide list and mention the row which you want...)

In [38]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


###### You have to print 1,3 and 4 row

In [39]:
print(a[[0,2,3]])

[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
a = np.arange(0,24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
print(a[[0,2,3,5]])

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]


In [42]:
print(a[:,[0,2,3]])

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


##### 3.Boolean Indexing

In [44]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[43, 85, 96, 24],
       [87, 19, 58, 96],
       [42, 15,  4, 32],
       [93, 45, 93, 63],
       [80, 51, 67,  9],
       [21, 61, 31, 72]])

In [46]:
# Find all numbers greater than 50
a>50
# Now can use it at mask where only true one will obtain i.e greater than 50

array([[False,  True,  True, False],
       [ True, False,  True,  True],
       [False, False, False, False],
       [ True, False,  True,  True],
       [ True,  True,  True, False],
       [False,  True, False,  True]])

In [47]:
a[a>50]

array([85, 96, 87, 58, 96, 93, 93, 63, 80, 51, 67, 61, 72])

In [50]:
# Find out all even numbers of given array a 
print(a%2 == 0) # this will give you boolean expression 
print(a[a%2==0])

[[False False  True  True]
 [False False  True  True]
 [ True False  True  True]
 [False False False False]
 [ True False False False]
 [False False False  True]]
[96 24 58 96 42  4 32 80 72]


In [ ]:
# Find all numbers greater than 50 and are even

In [57]:
a[(a>50) & (a%2==0)]
# NOTE: Here we use & but not this and coz & is boolean relational so we use this one here we're dealing with boolean  

array([96, 58, 96, 80, 72])

In [58]:
# find all numbers which are  not divisible by 7

In [59]:
a[~(a%7 == 0)]
# here ~ is used so that it will reverse the value bcz a%7==0 gives that no which are divisible by 7 

array([43, 85, 96, 24, 87, 19, 58, 96, 15,  4, 32, 93, 45, 93, 80, 51, 67,
        9, 61, 31, 72])

#### Broadcasting
##### .The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
##### .The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [61]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [62]:
# different shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

##### 1. Make the two arrays have the same number of dimensions.**<br>
###### If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

##### 2. Make each dimension of the two arrays the same size.**<br>
###### .If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
###### .If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [ ]:
# Examples for clarification

In [65]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


###### Above code is run easily as 1st array of (4,3) and 2nd one is (3) so introduce 1 to the head by rule 1 then it becomes (1,3) and now by rule 2 it head (i.e 1 ) is streched to 4 for matching (4,3) and hence broadcasting is done 

In [66]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

###### This code throws error i.e broadcasting cannot be done bcz 1st is (3,4) and 2nd is (3) so we can introduce 1 to the head then it becomes (1,3) and now strech 1 to the 3 so it finally becomes (3,3) which is not equal to 1st array (3,4) and hence broadcasting cannoot be done. 

In [82]:
# Que 3
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print(b)
print(a+b)
# Here in a.. 1 is treched to 3 which becomes(3,3) and in b 1 is streched to 3 becomes (3,3) hence broadcasting can be done

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [83]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [84]:
a = np.array([1])
# Shape -->> (1,1)
b = np.arange(4).reshape(2,2)
# Shape-->>> (2,2)
print(a)
print(b)
print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [85]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
print(a)
print(b)
print(a+b)
# NOTE: Here streching cannot be done because there is no 1 at any place (Rule 3) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [86]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)
# NOTE: Here streching cannot be done because there is no 1 at any place (Rule 3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

#### Working with mathematical formulas

In [93]:
# sigmoid-->> formulae is 1/(1+e^-x) and as there is no any built-in function so we make it 
def sigmoid(array):
    return 1/(1+np.exp(-(array)))

a = np.arange(20)
sigmoid(a)
# NOTE: sigmoid brings any number into range b/w 0 to 1

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999])

In [101]:
# mean squared error(MSE) -->> (actual-predicted)^2 = MSE 
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)
print(actual)
print(predicted)

def mse(actual,predicted):
    return np.mean((actual-predicted)**2)
mse(actual,predicted)

[18 18  2 36 41 47 26  7 20 44 45 32 42 47  3 34  5 15 11 16 27  3 22 14
 31]
[ 8 39 13 31 12  1 43 31 47 33 36  4 28 11 18  6 37 10 19 49  5 34 13 28
 39]


508.52

In [102]:
# binary cross entropy
np.mean((actual-predicted)**2)

508.52

In [103]:
# categorical cross entropy --- >> do it by yourself use formula from google


#### Working with missing values

In [107]:
# working with missing values -->> np.nan
a = np.array((1,2,3,4,np.nan,6))
a
# In output nan shows that missing value at that place

array([ 1.,  2.,  3.,  4., nan,  6.])

#### Plotting Graphs

In [110]:
# plotting a 2D plot
# x = y