## Numpy Tricks

#### NOTE: If output dikhne lage it means temporary changes but if output not shows it means permanent changes 

#### 1. np.sort

##### Return a sorted copy of an array

In [169]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [170]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[90, 94, 47, 83],
       [72, 67, 76, 91],
       [41, 14, 45, 34],
       [24,  8, 51, 12],
       [21, 98, 67,  1],
       [89, 73, 72, 14]])

In [171]:
# 1D Sorting
np.sort(a)

array([ 1,  1,  2,  6,  9,  9, 15, 28, 54, 62, 63, 66, 84, 88, 93])

In [172]:
# 2D sorting
np.sort(b)

array([[47, 83, 90, 94],
       [67, 72, 76, 91],
       [14, 34, 41, 45],
       [ 8, 12, 24, 51],
       [ 1, 21, 67, 98],
       [14, 72, 73, 89]])

In [173]:
# In 2D if you want column wise sorting-->> use axis = 0
np.sort(b,axis=0)

array([[21,  8, 45,  1],
       [24, 14, 47, 12],
       [41, 67, 51, 14],
       [72, 73, 67, 34],
       [89, 94, 72, 83],
       [90, 98, 76, 91]])

In [174]:
# If you want to sort in descending order -->>> use [::-1]
np.sort(a)[::-1]

array([93, 88, 84, 66, 63, 62, 54, 28, 15,  9,  9,  6,  2,  1,  1])

#### 2. np.append

##### The numpy.append() appends values along the mentioned axis at the end of the array 

In [175]:
# In 1D array
np.append(a,200)

array([ 15,  93,   9,   1,  62,   1,  54,   6,  88,  66,  84,  28,   2,
         9,  63, 200])

In [176]:
print(b)

[[90 94 47 83]
 [72 67 76 91]
 [41 14 45 34]
 [24  8 51 12]
 [21 98 67  1]
 [89 73 72 14]]


In [177]:
# In 2D array
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[90.        , 94.        , 47.        , 83.        ,  0.63363549],
       [72.        , 67.        , 76.        , 91.        ,  0.29588686],
       [41.        , 14.        , 45.        , 34.        ,  0.24696368],
       [24.        ,  8.        , 51.        , 12.        ,  0.66395777],
       [21.        , 98.        , 67.        ,  1.        ,  0.49380909],
       [89.        , 73.        , 72.        , 14.        ,  0.52929528]])

#### 3. np.concatenate

##### numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [178]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [179]:
np.concatenate((c,d),axis=0) # row-wise concatenation

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [180]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

#### 4. np.unique

##### With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method

In [181]:
e = np.array([1,2,2,3,3,4,4,5,5,6,6])

In [182]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#### 5. np.expand_dims

##### With the help of Numpy.expand_dims() method we can get the expanded dimensions of an array

In [183]:
# code
print(a)
print(a.shape)

[15 93  9  1 62  1 54  6 88 66 84 28  2  9 63]
(15,)


In [184]:
# NOTE: a and aa bth are same 
aa = np.expand_dims(a,axis=0)
print(aa)
print(aa.shape)
# Now the array a becomes 2D as its shapes is (1,15)

[[15 93  9  1 62  1 54  6 88 66 84 28  2  9 63]]
(1, 15)


In [185]:
aa = np.expand_dims(a,axis=1)
print(aa)
print(aa.shape)

[[15]
 [93]
 [ 9]
 [ 1]
 [62]
 [ 1]
 [54]
 [ 6]
 [88]
 [66]
 [84]
 [28]
 [ 2]
 [ 9]
 [63]]
(15, 1)


#### 6. np.where

##### The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied

In [186]:
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [187]:
# Find all indices with values greater than 50
np.where(a>50)

(array([ 1,  4,  6,  8,  9, 10, 14], dtype=int64),)

In [188]:
# replace all values > 50mwith 0
np.where(a>50,0,a)

array([15,  0,  9,  1,  0,  1,  0,  6,  0,  0,  0, 28,  2,  9,  0])

In [189]:
# replace all even nos in a with 0
np.where(a%2==0,0,a)

array([15, 93,  9,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  9, 63])

#### 7. np.argmax

##### The numpy.argmax() function return indices of the max element of the array in a particular axis.

In [190]:
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [191]:
np.argmax(a)

1

In [192]:
b

array([[90, 94, 47, 83],
       [72, 67, 76, 91],
       [41, 14, 45, 34],
       [24,  8, 51, 12],
       [21, 98, 67,  1],
       [89, 73, 72, 14]])

In [193]:
np.argmax(b,axis=0)
# 5,3,5,5 showing at that particular index in each column there would be maximum value

array([0, 4, 1, 1], dtype=int64)

In [194]:
np.argmax(b,axis=1)
# 1,3,2,1,1,3 showing at that particular index in each row there would be maximum value

array([1, 3, 2, 2, 1, 0], dtype=int64)

#### 8. np.cumsum -->> cummulative sum

In [195]:
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [196]:
# In 1D array
np.cumsum(a)

array([ 15, 108, 117, 118, 180, 181, 235, 241, 329, 395, 479, 507, 509,
       518, 581])

In [197]:
# In 2D array -->> must have to provide axis otherwise it converts it into 1D
b

array([[90, 94, 47, 83],
       [72, 67, 76, 91],
       [41, 14, 45, 34],
       [24,  8, 51, 12],
       [21, 98, 67,  1],
       [89, 73, 72, 14]])

In [198]:
np.cumsum(b,axis=0) # Column-wise so use axis=0

array([[ 90,  94,  47,  83],
       [162, 161, 123, 174],
       [203, 175, 168, 208],
       [227, 183, 219, 220],
       [248, 281, 286, 221],
       [337, 354, 358, 235]])

In [199]:
np.cumsum(b,axis=1) # row-wise hence use axis=1

array([[ 90, 184, 231, 314],
       [ 72, 139, 215, 306],
       [ 41,  55, 100, 134],
       [ 24,  32,  83,  95],
       [ 21, 119, 186, 187],
       [ 89, 162, 234, 248]])

#### 9. np.cumprod -->> same as cumsum

In [200]:
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [201]:
np.cumprod(a)

array([        15,       1395,      12555,      12555,     778410,
           778410,   42034140,  252204840,  719189440,  221862784,
       1456604672, 2130225152,  -34516992, -310652928, 1903702016])

#### 10. np.percentile

##### numpy.percentile() function used to compute the nth percentile of the given data(array elements) along the specified axis  --> np.percentile(a,percentile you want to know)

In [202]:
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [203]:
# 100th percentile is maximum hence in output 96 is obtained bcz max is 96
np.percentile(a,100)

93.0

In [204]:
# 0th percentile is minimum hence in output 5 is obtained bcz min is 5
np.percentile(a,0)

1.0

In [205]:
# 50th  percentile is the median of given a -->> hence in output 25 is obtained bcz median of a is 25
np.percentile(a,50)
# We can check the median of a by np.median(a)

28.0

In [206]:
np.median(a)

28.0

#### np.histogram

##### Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [207]:
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [208]:
np.histogram(a,bins=[0,50,100])
# here 0,50,100 is used to check that how many nos lies b/w 0-50 then 50-100 and ans is 0-50 = 11 nos and 50-100 = 4 nos

(array([8, 7], dtype=int64), array([  0,  50, 100]))

#### np.corrcoef 

##### Return Pearson product-moment correlation coefficients (always lies b/w -1 to 1)
###### . If 0 -->> there is no correlation b/w any two parameter
###### . If 1 -->> both are positively correlated (same amount se growth in both)
###### . If -1 ->> both are negatively correlated (if any particular amount one is increase then at the same amount another will decrease)

In [209]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

#### np.isin

###### With the help of numpy.isin() method, we can see that one array haviing values are checked in a different numpy array having different elements with different sizes.

###### NOTE: If you want to search multiple item at a time that these are present or not in given array then we use np.isin


In [210]:
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [211]:
items = [5,10,20,30,40,50,60,70,82,90,100]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [212]:
# now put in a to get which ones are present
a[np.isin(a,items)]

array([], dtype=int32)

#### np.flip

###### The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [213]:
print(a)

[15 93  9  1 62  1 54  6 88 66 84 28  2  9 63]


In [214]:
print(np.flip(a))

[63  9  2 28 84 66 88  6 54  1 62  1  9 93 15]


In [215]:
# Also works on 2D
print(b)

[[90 94 47 83]
 [72 67 76 91]
 [41 14 45 34]
 [24  8 51 12]
 [21 98 67  1]
 [89 73 72 14]]


In [216]:
print(np.flip(b))
# These output is because here two flipping is done 1st row and then column

[[14 72 73 89]
 [ 1 67 98 21]
 [12 51  8 24]
 [34 45 14 41]
 [91 76 67 72]
 [83 47 94 90]]


In [217]:
# Column-wise flipping
print(np.flip(b,axis=0))

[[89 73 72 14]
 [21 98 67  1]
 [24  8 51 12]
 [41 14 45 34]
 [72 67 76 91]
 [90 94 47 83]]


In [218]:
# Row-wise flipping
print(np.flip(b,axis=1))

[[83 47 94 90]
 [91 76 67 72]
 [34 45 14 41]
 [12 51  8 24]
 [ 1 67 98 21]
 [14 72 73 89]]


#### np.put

###### The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [219]:
# Code
a

array([15, 93,  9,  1, 62,  1, 54,  6, 88, 66, 84, 28,  2,  9, 63])

In [220]:
np.put(a,[0,1],[500,450])

In [221]:
a

array([500, 450,   9,   1,  62,   1,  54,   6,  88,  66,  84,  28,   2,
         9,  63])

#### np.delete

###### The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [222]:
a

array([500, 450,   9,   1,  62,   1,  54,   6,  88,  66,  84,  28,   2,
         9,  63])

In [225]:
# You've to provide the index no at which you want to delete the element
np.delete(a,0)

array([450,   9,   1,  62,   1,  54,   6,  88,  66,  84,  28,   2,   9,
        63])

In [226]:
# you can delete multiple items at a time
np.delete(a,[0,3,4])

array([450,   9,   1,  54,   6,  88,  66,  84,  28,   2,   9,  63])

#### Set Functions

###### . np.union1d
###### . np.intersect1d
###### . np.setdiff1d
###### . np.setxor1d
###### . np.in1d

In [227]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [228]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [229]:
np.intersect1d(m,n)

array([3, 4, 5])

In [231]:
# settdiff1d(m,n) -->> items present in m but not in n
np.setdiff1d(m,n)

array([1, 2])

In [232]:
# settdiff1d(n,m) -->> items present in n but not in m
np.setdiff1d(n,m)

array([6, 7])

In [234]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [235]:
# checks whether element is present in the set or not ?? 
np.in1d(m,1)

array([ True, False, False, False, False])

In [236]:
m[np.in1d(m,1)]

array([1])

#### np.clip

###### numpy.clip() function is used to Clip(limit) the values in an array 

###### NOTE: By using np.clip(a,a_min=x,a_max=y) we set a limit of values i.e a_min=x and a_max= y so all values greater than y are replaced with y and values less than x are replaced with x and others are same.

In [240]:
a

array([500, 450,   9,   1,  62,   1,  54,   6,  88,  66,  84,  28,   2,
         9,  63])

In [241]:
np.clip(a,a_min=25,a_max=75)
# here values greater than 75 are replaced with 75 and values less than 25 are replaced with 25 and others are same as

array([75, 75, 25, 25, 62, 25, 54, 25, 75, 66, 75, 28, 25, 25, 63])